name: uni_match
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_modular: ^3.3.1
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  # FIREBASE Packages Section
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  google_mobile_ads: ^0.12.1+1
    # END

  # This plugin help us to Sell VIP Subscription Plans in app
  in_app_purchase: ^0.5.2 #Olhar os bugs

  # This plugin help us to query users by geolocation center
  geoflutterfire: ^3.0.1

  # This plugin help us to use custom svg icons
  flutter_svg: ^0.22.0

  # Used to Select User Country Code
  country_code_picker: ^2.0.2

  # Used to Manage Application State
  scoped_model: ^2.0.0-nullsafety.0

  # Used to select images from the User's device image library or take a new photo using the camera
  image_picker: ^0.8.3+2

  # Used to Crop/Rotate Selected images from user's device
  image_cropper: ^1.4.1

  # Used to open link schemes in application or browser
  url_launcher: ^6.0.3

  # Used to get User location by GPS
  geolocator: ^7.4.0

  # Used to translate User latitude and longitude coordinates into a readable address
  geocoding: ^2.0.0

  # This plugin help us to create Passport feature
  place_picker: ^0.9.19-nullsafety

  # Used to create placeholder widget while app is loading the image
  shimmer: ^2.0.0

  # Used to create fuzzy timestamps: (e.g. "3 minutes ago")
  timeago: ^3.1.0

  # Used to share application content in other applications
  share: ^2.0.4

  #Tradução para pt-Br de alguns componentes
  flutter_cupertino_localizations: ^1.0.1

  #Biblioteca para alerta em widget
  rflutter_alert: ^2.0.4

  #Biblioteca de tipos de carregamentos
  flutter_spinkit: ^5.0.0

  #Biblioteca de tipos de Formatters
  brasil_fields: ^1.1.4

  #Biblioteca para story instagram
  story: ^0.5.1

  #Biblioteca para animação em list
  flutter_staggered_animations: ^1.0.0

  #Biblioteca para animação
  lottie: ^1.1.0

  #Biblioteca para animação
  animator: ^3.1.0

  #Biblioteca para animação
  flare_flutter: ^3.0.2

  #Biblioteca para salvar dados em cash
  shared_preferences: ^2.0.6

  #Biblioteca para enviar para maps
  map_launcher: ^2.1.1

  #Biblioteca para machine learning
  google_ml_kit: ^0.7.0

  #Biblioteca para buscar horas GTM - 00:00
  ntp: ^2.0.0

  #Biblioteca para contar tempo
  custom_timer: ^0.0.6

  #Biblioteca de fontes
  google_fonts: ^2.1.0

  #Biblioteca de arrastar pro lado
  swipe_to: 0.1.0-nullsafety.1

  #Biblioteca de emoji_picker_flutter:
  emoji_picker_flutter: ^1.0.6

  #Biblioteca de animação
  animate_do: ^2.0.0

  #Biblioteca do botao de reacao
  flutter_reaction_button: ^1.0.8

  #Biblioteca de visibilidade do teclado
  flutter_keyboard_visibility: ^5.0.3


  flutter_cupertino_datetime_picker: ^2.0.1

dev_dependencies:
  #Biblioteca para splash_screen nativo
  flutter_native_splash: ^1.2.1

  #Biblioteca para icone do app
  flutter_launcher_icons: ^0.9.1
  #Biblioteca de acoes do teclado
  keyboard_actions: ^3.4.3

  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/flare/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  image: assets/images/app_logo_white.png
  color: "#e91e63"