name: uni_match
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_modular: ^3.4.1+1
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2


    # FIREBASE Packages Section
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  firebase_messaging: ^10.0.6
  firebase_storage: ^10.0.3

    # GOOGLE Packages Section
  google_mobile_ads: ^0.12.1+1
  google_fonts: ^2.1.0
  google_ml_vision: ^0.0.7
  #Biblioteca para machine learning
  # END

    # Este plugin nos ajuda a vender planos de assinatura VIP no aplicativo
  in_app_purchase: ^1.0.8

    # Este plugin nos ajuda a consultar usuários por centro de geolocalização
  geoflutterfire: ^3.0.1

    # Usado para obter a localização do usuário por GPS
  geolocator: ^7.6.0

    # Used to translate User latitude and longitude coordinates into a readable address
  geocoding: ^2.0.1

    #Biblioteca para enviar para maps
  map_launcher: ^2.1.1

    # Este plugin nos ajuda a usar ícones SVG personalizados
  flutter_svg: ^0.22.0

    # Usado para gerenciar o estado do aplicativo Bloc**
  scoped_model: ^2.0.0-nullsafety.0

    # Usado para selecionar imagens do celular
  image_picker: ^0.8.4

    # Usado para cortar / girar imagens selecionadas do dispositivo do usuário
  image_cropper: ^1.4.1

  # Usado para dar zoom em imagens
  photo_view: ^0.12.0

  # Usado para guardar imagens em cach
  cached_network_image: ^3.1.0

    # Usado para abrir link no aplicativo ou navegador
  url_launcher: ^6.0.3

    # Este plugin nos ajuda a criar o recurso Passport
  place_picker: ^0.9.19-nullsafety

    # Usado para criar widget de espaço reservado enquanto o aplicativo está carregando a imagem
  shimmer: ^2.0.0

    # Usado para criar carimbos de data / hora difusos: (por exemplo, "3 minutos atrás")
  timeago: ^3.1.0

    # Usado para compartilhar o conteúdo do aplicativo em outros aplicativos
  share: ^2.0.4

    #Tradução para pt-Br de alguns componentes
  flutter_cupertino_localizations: ^1.0.1

    #Biblioteca para alerta em widget
  rflutter_alert: ^2.0.4

    #Biblioteca de tipos de carregamentos
  flutter_spinkit: ^5.1.0

    #Biblioteca de tipos de Formatters
  brasil_fields: ^1.1.4

    #Biblioteca para story instagram
  story: ^0.5.1

    #Biblioteca para animação em list
  flutter_staggered_animations: ^1.0.0

    #Biblioteca para animação
  lottie: ^1.1.0

    #Biblioteca para animação
  animator: ^3.1.0

    #Biblioteca para animação
  flare_flutter: ^3.0.2

    #Biblioteca para salvar dados em cash
  shared_preferences: ^2.0.7

    #Biblioteca para buscar horas GTM - 00:00
  ntp: ^2.0.0

    #Biblioteca para contar tempo
  custom_timer: ^0.0.6

    #Biblioteca de arrastar pro lado
  swipe_to: 0.1.0-nullsafety.1

    #Biblioteca de emoji_picker_flutter:
  emoji_picker_flutter: ^1.0.7

    #Biblioteca de animação
  animate_do: ^2.0.0

    #Biblioteca do botao de reacao
  flutter_reaction_button: ^1.0.8

    #Biblioteca para validar e-mail
  email_validator: ^2.0.1

    #Biblioteca para info
  fluttertoast: ^8.0.8

    #Biblioteca para intro
  liquid_swipe: ^2.1.0

    #Biblioteca para responsividade
  responsive_framework: ^0.1.4

  #Biblioteca de visibilidade do teclado
  flutter_keyboard_visibility: ^5.0.3

  intl: ^0.17.0

  flutter_cupertino_datetime_picker: ^2.0.1
  dio: ^4.0.0

dev_dependencies:
  #Biblioteca para splash_screen nativo
  flutter_native_splash: ^1.2.1

  #Biblioteca para icone do app
  flutter_launcher_icons: ^0.9.2

  #Biblioteca de acoes do teclado
  keyboard_actions: ^3.4.4

  flutter_modular_test: ^1.0.3
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/lang/
     - assets/flare/
     - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  image: assets/images/app_logo_white.png
  color: "#FFFFFF"